package com.examplemybatis.demo.dao;

import com.examplemybatis.demo.entity.Driver;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
public interface DriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int insertSelective(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    Driver selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int updateByPrimaryKeySelective(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int updateByPrimaryKey(Driver record);
}