package com.examplemybatis.demo.dao;

import com.examplemybatis.demo.entity.Journey;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
public interface JourneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int insert(Journey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int insertSelective(Journey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    Journey selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int updateByPrimaryKeySelective(Journey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    int updateByPrimaryKey(Journey record);
}