package com.examplemybatis.demo.entity;

public class Driver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.id
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.name
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.username
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.password
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Driver(Long id, String name, String username, String password) {
        this.id = id;
        this.name = name;
        this.username = username;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Driver() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.id
     *
     * @return the value of driver.id
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.id
     *
     * @param id the value for driver.id
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.name
     *
     * @return the value of driver.name
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.name
     *
     * @param name the value for driver.name
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.username
     *
     * @return the value of driver.username
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.username
     *
     * @param username the value for driver.username
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.password
     *
     * @return the value of driver.password
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.password
     *
     * @param password the value for driver.password
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}