package com.examplemybatis.demo.entity;

import java.util.Date;

public class Journey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.id
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.carId
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private Long carid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.start
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private Date start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.arrival
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private Date arrival;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.gain
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private Long gain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.passengers
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private Integer passengers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.remark
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Journey(Long id, Long carid, Date start, Date arrival, Long gain, Integer passengers, String remark) {
        this.id = id;
        this.carid = carid;
        this.start = start;
        this.arrival = arrival;
        this.gain = gain;
        this.passengers = passengers;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Journey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.id
     *
     * @return the value of journey.id
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.id
     *
     * @param id the value for journey.id
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.carId
     *
     * @return the value of journey.carId
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Long getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.carId
     *
     * @param carid the value for journey.carId
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setCarid(Long carid) {
        this.carid = carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.start
     *
     * @return the value of journey.start
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.start
     *
     * @param start the value for journey.start
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.arrival
     *
     * @return the value of journey.arrival
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Date getArrival() {
        return arrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.arrival
     *
     * @param arrival the value for journey.arrival
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setArrival(Date arrival) {
        this.arrival = arrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.gain
     *
     * @return the value of journey.gain
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Long getGain() {
        return gain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.gain
     *
     * @param gain the value for journey.gain
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setGain(Long gain) {
        this.gain = gain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.passengers
     *
     * @return the value of journey.passengers
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public Integer getPassengers() {
        return passengers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.passengers
     *
     * @param passengers the value for journey.passengers
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setPassengers(Integer passengers) {
        this.passengers = passengers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.remark
     *
     * @return the value of journey.remark
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.remark
     *
     * @param remark the value for journey.remark
     *
     * @mbggenerated Wed Dec 04 13:04:16 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}